### ISSUE TITLE
Club meeting recording doesn't like slack @s

### ISSUE THREAD

**Issue by thatrobotdev** [hackclub/orpheus-bot#10]
When Orpheus asks for a meeting to be recorded, she doesn't deal with usernames correctly.
![image](https://user-images.githubusercontent.com/18013689/72868060-24e97380-3c9e-11ea-87e6-a4d7f8d677b0.png)

I would probably expect Orpheus to give an error message, or not reply at all.

**Comment by HarrisonLKatz** [comment]
@'s get turned into ids, so probably the id contained the number. Maybe the bot should ignore anything in <>?

**Comment by thatrobotdev** [comment]
What does a raw slack message look like with a user mention?

**Comment by lukec11** [comment]
It looks something like this:
<@UE8DH0UHM>

The middle number is Slack's account UID (unique to each user), so it could have contained the number

**Comment by maxwofford** [comment]
Attempted to fix with https://github.com/hackclub/orpheus-bot/commit/037d17d7f3a09f70cd06a00fd9420efc35f6368e
