### ISSUE TITLE
Orpheus "Thank You" Response

### ISSUE THREAD

**Issue by thatrobotdev** [hackclub/orpheus-bot#22]
![Orpheus slack message "u da best, dino 🦕" isn't understood by Orpheus.](https://user-images.githubusercontent.com/18013689/75077059-e3c3c980-54be-11ea-9d18-200f7cbc62cb.png)

"u da best, dino 🦕" isn't understood as a "Thank you" message.

**Comment by Rohan-GD** [comment]
Can I try solving this?

**Comment by lachlanjc** [comment]
Yeah of course @roshan-gd!

**Comment by Rohan-GD** [comment]
Alrighty
