### ISSUE TITLE
Should have flow to report "no meeting"

### ISSUE THREAD

**Issue by itsmingjie** [hackclub/orpheus-bot#6]
I have personally wondered about this (and my co-leaders) too -- what do we do when we didn't have a meeting, and Orpheus pings up? 

The current flow is not clear that we can simply skip check-ins, especially when there are green check marks on meetings we had. It feels like an obligation to have a green check mark on every single meeting ping.

It'd be great if we can have some sort of no-meeting reporting flow (e.g. replying "no meeting" in thread, or reacting with an X, etc.) and Orpheus will reply back with "Ok got it", even if it reports absolutely nothing to the database at all. Or... we can collect reasons of why clubs are not meeting, so we can follow-up when a club hasn't been meeting for a while. 

<3

**Comment by maxwofford** [comment]
Hey, sorry for not responding earlier. Just added a "respond with :no: if you didn't meet" line to the notification for the time being, but I also want to track non-meetings in the database.

This is actually the perfect time for this stuff b/c I'm working on defining active/inactive clubs & this'll go a long way in giving it a definition. Still need to think through implementation, but I'd love to hear your thoughts on something like this policy:

to apply for your second GitHub grant, you'll need to be an "active club". active clubs either:
- have met within the last month
- have responded to checkin notifications (saying you didn't meet counts) within the last 2 months

also, checkin notifications will only run for active clubs

active clubs can request to go 'inactive' to mute checkin notifications over winter break, then become active again by recording a meeting

**Comment by maxwofford** [comment]
hit send too soon. also wanted to mention this is totally just a brainstorm– haven't written this out before until now & want to get your honest thoughts about the direction

**Comment by itsmingjie** [comment]
Yup, this makes total sense! Think we can probably modify the definition of “active clubs” by a little bit but the overall process looks good. Feel free to DM me chat about active clubs, etc!

**Comment by MatthewStanciu** [comment]
Can this issue be closed? Seems like this feature was implemented.
